Fixed coverage setup.
There was no .coveragerc to restrict the files to check.  In fact, it was in the .gitignore file.
Travis pip installed coverage, which was already there.
Travis used coverage.pickle2json to convert .coverage file from v3 to v4, but we were already using v4, so that broke.

Travis also gave an error:

ERROR: Something went wrong when executing '/home/travis/build/collective/Products.PloneKeywordManager/bin/coverage html --directory=parts/test/coverage'
ERROR: Returncode: 1
ERROR: Output:
ERROR: No source for code: '/home/travis/build/collective/Products.PloneKeywordManager/parts/test/18751b0da9dbd048c270e84ef48a19d2.py'.
Aborting report output, consider using -i.

Result was that coverall reported that coverage remained the same at '?%'
https://coveralls.io/builds/23424458